// This file is generated by scripts/generate-content-manifest.ts.
// Do not edit it manually.

export const contentManifest = {
  "allArticleSlugs": [
    "carpenter-chef-painter-fatigue-pierna-recta",
    "sashiko-reparacion-textil-y-menswear",
    "chore-coat-workwear-fundacional",
    "algodon-fibra-larga-origen-calidad",
    "denim-japones-y-mito-americano",
    "m65-legado-civil",
    "aaron-levine-elegancia-casual",
    "ivy-ocbd-y-loafers",
    "chambray-y-fatiga",
    "wrangler-13mwz-icono-vaquero",
    "algodon-sarga-denim-canvas-duck-chambray",
    "dirty-dozen-relojes-militares-y-menswear",
    "sudaderas-crewneck-triangulo-cuello",
    "champion-reverse-weave-hoodies",
    "cone-mills-white-oak-gustin-deadstock",
    "buzz-rickson-atencion-al-detalle",
    "camisetas-loopwheeled-merz-whitesville",
    "donegal-tweed-neps-y-cultura-textil",
    "trucker-jackets-type-1-2-3",
    "german-army-trainers",
    "tartanes-de-casas-barbour-baracuta-y-otras",
    "mcgregor-drizzler-eisenhower",
    "n1-deck-jacket-y-version-rll",
    "rl67-jacket-importancia-menswear",
    "g1-leather-jacket",
    "woolrich-arctic-parka-frio-icono-civil"
  ],
  "latestArticleSlugs": [
    "carpenter-chef-painter-fatigue-pierna-recta",
    "sashiko-reparacion-textil-y-menswear",
    "chore-coat-workwear-fundacional",
    "algodon-fibra-larga-origen-calidad"
  ],
  "featuredArticleSlug": "chore-coat-workwear-fundacional",
  "articleBySlug": {
    "carpenter-chef-painter-fatigue-pierna-recta": {
      "slug": "carpenter-chef-painter-fatigue-pierna-recta",
      "popularityId": "carpenter-chef-painter-fatigue-pierna-recta",
      "title": "La pierna recta tiene cuatro talleres",
      "excerpt": "Carpenter, chef, painter y fatigue no son variantes intercambiables del mismo pantalón utilitario. Cada uno organiza bolsillos, tela y volumen según un trabajo distinto, y por eso también ofrecen rutas civiles muy distintas.",
      "publishedAt": "2026-03-14",
      "publishedLabel": "14 mar 2026",
      "readTime": "10 min",
      "category": "workwear",
      "categoryLabel": "Workwear",
      "storyType": "Variantes",
      "tags": [
        "Workwear",
        "Straight Leg",
        "Fatigue Pants"
      ],
      "heroImage": "https://images.unsplash.com/photo-1619759247378-6a73e3ad45f1?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Taller de carpintería con trabajadores y herramientas, un contexto útil para pensar la lógica del pantalón recto de oficio.",
      "relatedSlugs": [
        "chore-coat-workwear-fundacional",
        "chambray-y-fatiga",
        "sashiko-reparacion-textil-y-menswear"
      ],
      "resolvedRelatedSlugs": [
        "chore-coat-workwear-fundacional",
        "chambray-y-fatiga",
        "sashiko-reparacion-textil-y-menswear"
      ],
      "featured": false,
      "sections": [
        {
          "id": "carpenter-una-base-para-cargar-y-agacharse",
          "title": "Carpenter, una base para cargar y agacharse",
          "level": 2
        },
        {
          "id": "chef-ligereza-disciplinada-en-vez-de-epica-obrera",
          "title": "Chef, ligereza disciplinada en vez de épica obrera",
          "level": 2
        },
        {
          "id": "painter-blanco-barato-y-dispuesto-a-arruinarse",
          "title": "Painter, blanco, barato y dispuesto a arruinarse",
          "level": 2
        },
        {
          "id": "fatigue-la-utilidad-militar-cuando-todavia-no-es-disfraz",
          "title": "Fatigue, la utilidad militar cuando todavía no es disfraz",
          "level": 2
        },
        {
          "id": "cual-sobrevive-mejor-fuera-del-trabajo",
          "title": "Cuál sobrevive mejor fuera del trabajo",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/carpenter-chef-painter-fatigue-pierna-recta.mdx"
    },
    "sashiko-reparacion-textil-y-menswear": {
      "slug": "sashiko-reparacion-textil-y-menswear",
      "popularityId": "sashiko-reparacion-textil-y-menswear",
      "title": "La belleza útil de una ropa reparada",
      "excerpt": "Antes de convertirse en textura deseable para marcas y aficionados, el sashiko fue una técnica de puntada corrida ligada al refuerzo, la reparación y la administración severa de la ropa.",
      "publishedAt": "2026-03-13",
      "publishedLabel": "13 mar 2026",
      "readTime": "9 min",
      "category": "workwear",
      "categoryLabel": "Workwear",
      "storyType": "Historia",
      "tags": [
        "Sashiko",
        "Boro",
        "Workwear"
      ],
      "heroImage": "https://images.unsplash.com/photo-1516762689617-e1cffcef479d?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Textil azul índigo con costuras visibles de reparación y refuerzo.",
      "relatedSlugs": [
        "chore-coat-workwear-fundacional",
        "denim-japones-y-mito-americano",
        "chambray-y-fatiga"
      ],
      "resolvedRelatedSlugs": [
        "chore-coat-workwear-fundacional",
        "denim-japones-y-mito-americano",
        "chambray-y-fatiga"
      ],
      "featured": false,
      "sections": [
        {
          "id": "necesidad-antes-que-ornamento",
          "title": "Necesidad antes que ornamento",
          "level": 2
        },
        {
          "id": "sashiko-no-es-boro",
          "title": "Sashiko no es boro",
          "level": 2
        },
        {
          "id": "de-la-cultura-del-remiendo-a-la-moda",
          "title": "De la cultura del remiendo a la moda",
          "level": 2
        },
        {
          "id": "apropiacion-admiracion-y-malentendido",
          "title": "Apropiación, admiración y malentendido",
          "level": 2
        },
        {
          "id": "un-caso-contemporaneo-sashiko-gals",
          "title": "Un caso contemporáneo: Sashiko Gals",
          "level": 2
        },
        {
          "id": "lo-que-puede-ensenar-al-armario-actual",
          "title": "Lo que puede enseñar al armario actual",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/sashiko-reparacion-textil-y-menswear.mdx"
    },
    "chore-coat-workwear-fundacional": {
      "slug": "chore-coat-workwear-fundacional",
      "popularityId": "chore-coat-workwear-fundacional",
      "title": "Por qué la chore coat sigue siendo una chaqueta fundacional del workwear",
      "excerpt": "De la veste de travail francesa a la rotación contemporánea del denim, la chore coat sigue siendo una de las mejores puertas de entrada al workwear por su mezcla de utilidad, textura y memoria obrera.",
      "publishedAt": "2026-03-10",
      "publishedLabel": "10 mar 2026",
      "readTime": "8 min",
      "category": "workwear",
      "categoryLabel": "Workwear",
      "storyType": "Iconos",
      "tags": [
        "Workwear",
        "Chore Coat",
        "Denim"
      ],
      "heroImage": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Chaqueta de trabajo azul colgada junto a otras prendas de herencia utilitaria.",
      "relatedSlugs": [
        "chambray-y-fatiga",
        "m65-legado-civil"
      ],
      "resolvedRelatedSlugs": [
        "chambray-y-fatiga",
        "m65-legado-civil"
      ],
      "featured": true,
      "sections": [
        {
          "id": "lo-que-hace-bien-la-chore-coat",
          "title": "Lo que hace bien la chore coat",
          "level": 2
        },
        {
          "id": "por-que-sigue-funcionando-hoy",
          "title": "Por qué sigue funcionando hoy",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/chore-coat-workwear-fundacional.mdx"
    },
    "algodon-fibra-larga-origen-calidad": {
      "slug": "algodon-fibra-larga-origen-calidad",
      "popularityId": "algodon-fibra-larga-origen-calidad",
      "title": "No todo el algodón nace igual",
      "excerpt": "Hablar de algodón como si fuera una sola cosa empobrece la conversación. Longitud de fibra, origen, limpieza, hilatura y cultivo cambian por completo lo que una tela puede llegar a ser.",
      "publishedAt": "2026-03-07",
      "publishedLabel": "7 mar 2026",
      "readTime": "11 min",
      "category": null,
      "categoryLabel": null,
      "storyType": "Lo Básico",
      "tags": [
        "Algodón",
        "Tejidos",
        "Pima",
        "FoxFibre",
        "Denim"
      ],
      "heroImage": "https://unsplash.com/photos/7tCyoE0mgD8/download?force=true&w=1600",
      "heroAlt": "Cápsulas de algodón abiertas en una planta, mostrando la fibra blanca antes del hilado.",
      "relatedSlugs": [
        "algodon-sarga-denim-canvas-duck-chambray",
        "denim-japones-y-mito-americano",
        "camisetas-loopwheeled-merz-whitesville"
      ],
      "resolvedRelatedSlugs": [
        "algodon-sarga-denim-canvas-duck-chambray",
        "denim-japones-y-mito-americano",
        "camisetas-loopwheeled-merz-whitesville"
      ],
      "featured": false,
      "sections": [
        {
          "id": "la-primera-jerarquia-esta-en-la-longitud-de-la-fibra",
          "title": "La primera jerarquía está en la longitud de la fibra",
          "level": 2
        },
        {
          "id": "pima-no-es-un-sinonimo-elegante-de-algodon-bueno",
          "title": "Pima no es un sinónimo elegante de algodón bueno",
          "level": 2
        },
        {
          "id": "el-algodon-corriente-no-es-necesariamente-malo",
          "title": "El algodón corriente no es necesariamente malo",
          "level": 2
        },
        {
          "id": "organico-una-virtud-real-pero-no-una-absolucion-automatica",
          "title": "Orgánico: una virtud real, pero no una absolución automática",
          "level": 2
        },
        {
          "id": "foxfibre-demuestra-que-el-color-tambien-puede-empezar-en-la-planta",
          "title": "FoxFibre demuestra que el color también puede empezar en la planta",
          "level": 2
        },
        {
          "id": "el-origen-si-importa-pero-no-como-pasaporte-magico",
          "title": "El origen sí importa, pero no como pasaporte mágico",
          "level": 2
        },
        {
          "id": "por-que-algunas-casas-japonesas-de-denim-hablan-tanto-de-zimbabue",
          "title": "Por qué algunas casas japonesas de denim hablan tanto de Zimbabue",
          "level": 2
        },
        {
          "id": "que-significa-calidad-cuando-hablamos-de-algodon",
          "title": "Qué significa “calidad” cuando hablamos de algodón",
          "level": 2
        },
        {
          "id": "una-mejor-manera-de-mirar-la-etiqueta",
          "title": "Una mejor manera de mirar la etiqueta",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/algodon-fibra-larga-origen-calidad.mdx"
    },
    "denim-japones-y-mito-americano": {
      "slug": "denim-japones-y-mito-americano",
      "popularityId": "denim-japones-y-mito-americano",
      "title": "Por qué el denim japonés se volvió la conciencia del mito americano",
      "excerpt": "La autenticidad en el denim nunca fue solo una cuestión de origen geográfico; es una narrativa de trabajo, reproducción histórica y deseo cultural.",
      "publishedAt": "2026-03-03",
      "publishedLabel": "3 mar 2026",
      "readTime": "9 min",
      "category": "vintage-americana",
      "categoryLabel": "Vintage Americana",
      "storyType": "Historia",
      "tags": [
        "Americana",
        "Denim Japonés",
        "Heritage"
      ],
      "heroImage": "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Denim oscuro con costuras visibles y textura marcada.",
      "relatedSlugs": [
        "chore-coat-workwear-fundacional",
        "ivy-ocbd-y-loafers"
      ],
      "resolvedRelatedSlugs": [
        "chore-coat-workwear-fundacional",
        "ivy-ocbd-y-loafers"
      ],
      "featured": false,
      "sections": [
        {
          "id": "el-giro-japones",
          "title": "El giro japonés",
          "level": 2
        },
        {
          "id": "por-que-sigue-importando",
          "title": "Por qué sigue importando",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/denim-japones-y-mito-americano.mdx"
    },
    "m65-legado-civil": {
      "slug": "m65-legado-civil",
      "popularityId": "m65-legado-civil",
      "title": "La M-65 no necesita nostalgia",
      "excerpt": "La field jacket M-65 no solo resolvió una necesidad operacional; también definió una silueta civil donde bolsillos, volumen y utilidad siguen teniendo autoridad.",
      "publishedAt": "2026-02-24",
      "publishedLabel": "24 feb 2026",
      "readTime": "7 min",
      "category": "military-heritage",
      "categoryLabel": "Military Heritage",
      "storyType": "Iconos",
      "tags": [
        "Militaria",
        "M-65",
        "Field Jacket"
      ],
      "heroImage": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Chaqueta verde oliva de inspiración militar sobre una pared neutra.",
      "relatedSlugs": [
        "chambray-y-fatiga",
        "chore-coat-workwear-fundacional"
      ],
      "resolvedRelatedSlugs": [
        "chambray-y-fatiga",
        "chore-coat-workwear-fundacional"
      ],
      "featured": false,
      "sections": [
        {
          "id": "del-uniforme-al-excedente-y-del-excedente-al-cine",
          "title": "Del uniforme al excedente, y del excedente al cine",
          "level": 2
        },
        {
          "id": "como-ensena-a-mirar-la-silueta",
          "title": "Cómo enseña a mirar la silueta",
          "level": 2
        },
        {
          "id": "su-vigencia-actual",
          "title": "Su vigencia actual",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/m65-legado-civil.mdx"
    },
    "aaron-levine-elegancia-casual": {
      "slug": "aaron-levine-elegancia-casual",
      "popularityId": "aaron-levine-elegancia-casual",
      "title": "Aaron Levine y una forma más adulta del casual americano",
      "excerpt": "Entre el sportswear y la sastrería blanda, Aaron Levine ha mostrado que el armario cotidiano puede ser relajado sin caer en la indiferencia visual.",
      "publishedAt": "2026-02-17",
      "publishedLabel": "17 feb 2026",
      "readTime": "7 min",
      "category": "elevated-casual",
      "categoryLabel": "Elevated Casual",
      "storyType": "Opinión",
      "tags": [
        "Elevated Casual",
        "Aaron Levine",
        "Sportswear"
      ],
      "heroImage": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Look casual refinado con chaqueta suave y camisa abierta.",
      "relatedSlugs": [
        "ivy-ocbd-y-loafers",
        "denim-japones-y-mito-americano"
      ],
      "resolvedRelatedSlugs": [
        "ivy-ocbd-y-loafers",
        "denim-japones-y-mito-americano"
      ],
      "featured": false,
      "sections": [
        {
          "id": "un-armario-de-piezas-discretas-no-de-gestos-grandilocuentes",
          "title": "Un armario de piezas discretas, no de gestos grandilocuentes",
          "level": 2
        },
        {
          "id": "una-paleta-mas-tranquila",
          "title": "Una paleta más tranquila",
          "level": 2
        },
        {
          "id": "por-que-esta-linea-sigue-interesando",
          "title": "Por qué esta línea sigue interesando",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/aaron-levine-elegancia-casual.mdx"
    },
    "ivy-ocbd-y-loafers": {
      "slug": "ivy-ocbd-y-loafers",
      "popularityId": "ivy-ocbd-y-loafers",
      "title": "Ivy sigue vivo cuando deja de parecer disfraz",
      "excerpt": "El estilo Ivy sobrevive porque combina disciplina visual y comodidad social. No depende del disfraz, sino de una sintaxis que sigue siendo útil.",
      "publishedAt": "2026-02-10",
      "publishedLabel": "10 feb 2026",
      "readTime": "8 min",
      "category": "ivy",
      "categoryLabel": "Ivy",
      "storyType": "Lo Básico",
      "tags": [
        "Ivy",
        "OCBD",
        "Loafers"
      ],
      "heroImage": "https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Look Ivy con americana suave, camisa oxford y mocasines.",
      "relatedSlugs": [
        "aaron-levine-elegancia-casual",
        "denim-japones-y-mito-americano"
      ],
      "resolvedRelatedSlugs": [
        "aaron-levine-elegancia-casual",
        "denim-japones-y-mito-americano"
      ],
      "featured": false,
      "sections": [
        {
          "id": "las-piezas-que-sostienen-el-sistema",
          "title": "Las piezas que sostienen el sistema",
          "level": 2
        },
        {
          "id": "un-lenguaje-vivo",
          "title": "Un lenguaje vivo",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/ivy-ocbd-y-loafers.mdx"
    },
    "chambray-y-fatiga": {
      "slug": "chambray-y-fatiga",
      "popularityId": "chambray-y-fatiga",
      "title": "Chambray, pantalones fatiga y la poesía utilitaria del armario diario",
      "excerpt": "Algunas combinaciones sobreviven porque distribuyen bien el peso visual. Chambray y fatiga forman una de las parejas más estables del menswear de herencia.",
      "publishedAt": "2026-02-03",
      "publishedLabel": "3 feb 2026",
      "readTime": "6 min",
      "category": "workwear",
      "categoryLabel": "Workwear",
      "storyType": "Cómo llevarlo",
      "tags": [
        "Chambray",
        "Fatigue Pants",
        "Daily Uniform"
      ],
      "heroImage": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Camisa chambray junto a pantalones verde oliva de estilo fatiga.",
      "relatedSlugs": [
        "m65-legado-civil",
        "chore-coat-workwear-fundacional"
      ],
      "resolvedRelatedSlugs": [
        "m65-legado-civil",
        "chore-coat-workwear-fundacional"
      ],
      "featured": false,
      "sections": [
        {
          "id": "por-que-funciona-tan-bien",
          "title": "Por qué funciona tan bien",
          "level": 2
        },
        {
          "id": "una-leccion-de-economia",
          "title": "Una lección de economía",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/chambray-y-fatiga.mdx"
    },
    "wrangler-13mwz-icono-vaquero": {
      "slug": "wrangler-13mwz-icono-vaquero",
      "popularityId": "wrangler-13mwz-icono-vaquero",
      "title": "El 13MWZ sabe caer sobre la bota",
      "excerpt": "El Wrangler 13MWZ no es solo un vaquero del Oeste. Es una de las pocas prendas que resolvió de verdad la relación entre montar, trabajar, caer bien sobre la bota y seguir viéndose correcta fuera del rodeo.",
      "publishedAt": "2026-02-01",
      "publishedLabel": "1 feb 2026",
      "readTime": "9 min",
      "category": "vintage-americana",
      "categoryLabel": "Vintage Americana",
      "storyType": "Iconos",
      "tags": [
        "Wrangler",
        "13MWZ",
        "Denim",
        "Rodeo",
        "Western"
      ],
      "heroImage": "https://unsplash.com/photos/vypxJJdCGxQ/download?force=true&w=1600",
      "heroAlt": "Vaquero con pantalón tejano recto y botas en un entorno rural abierto.",
      "relatedSlugs": [
        "denim-japones-y-mito-americano",
        "carpenter-chef-painter-fatigue-pierna-recta",
        "trucker-jackets-type-1-2-3"
      ],
      "resolvedRelatedSlugs": [
        "denim-japones-y-mito-americano",
        "carpenter-chef-painter-fatigue-pierna-recta",
        "trucker-jackets-type-1-2-3"
      ],
      "featured": false,
      "sections": [
        {
          "id": "un-pantalon-dibujado-desde-la-silla-de-montar",
          "title": "Un pantalón dibujado desde la silla de montar",
          "level": 2
        },
        {
          "id": "por-que-fue-distinto-dentro-del-denim-americano",
          "title": "Por qué fue distinto dentro del denim americano",
          "level": 2
        },
        {
          "id": "quienes-lo-llevaron-de-verdad",
          "title": "Quiénes lo llevaron de verdad",
          "level": 2
        },
        {
          "id": "la-pierna-pensada-para-bota-es-la-mitad-de-la-historia",
          "title": "La pierna pensada para bota es la mitad de la historia",
          "level": 2
        },
        {
          "id": "por-que-sigue-siendo-un-icono",
          "title": "Por qué sigue siendo un icono",
          "level": 2
        },
        {
          "id": "como-leerlo-hoy-sin-convertirlo-en-disfraz",
          "title": "Cómo leerlo hoy sin convertirlo en disfraz",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/wrangler-13mwz-icono-vaquero.mdx"
    },
    "algodon-sarga-denim-canvas-duck-chambray": {
      "slug": "algodon-sarga-denim-canvas-duck-chambray",
      "popularityId": "algodon-sarga-denim-canvas-duck-chambray",
      "title": "Algodón, sarga, denim, canvas y otras diferencias que sí importan",
      "excerpt": "Denim, canvas, duck, chambray, drill y twill suelen meterse en el mismo cajón, pero no nombran la misma cosa. Entender su estructura cambia por completo la manera de leer peso, caída, desgaste y uso.",
      "publishedAt": "2026-01-15",
      "publishedLabel": "15 ene 2026",
      "readTime": "10 min",
      "category": null,
      "categoryLabel": null,
      "storyType": "Variantes",
      "tags": [
        "Denim",
        "Chambray",
        "Canvas",
        "Duck Canvas",
        "Drill",
        "Twill"
      ],
      "heroImage": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Tejidos de algodón azul y crudo doblados, mostrando superficies distintas y densidades variables.",
      "relatedSlugs": [
        "chambray-y-fatiga",
        "denim-japones-y-mito-americano",
        "chore-coat-workwear-fundacional"
      ],
      "resolvedRelatedSlugs": [
        "chambray-y-fatiga",
        "denim-japones-y-mito-americano",
        "chore-coat-workwear-fundacional"
      ],
      "featured": false,
      "sections": [
        {
          "id": "la-pregunta-correcta-no-es-el-nombre-sino-la-estructura",
          "title": "La pregunta correcta no es el nombre, sino la estructura",
          "level": 2
        },
        {
          "id": "twill-o-sarga-la-familia-que-dobla-mejor",
          "title": "Twill o sarga, la familia que dobla mejor",
          "level": 2
        },
        {
          "id": "denim-una-sarga-que-cuenta-la-vida-en-alto-contraste",
          "title": "Denim, una sarga que cuenta la vida en alto contraste",
          "level": 2
        },
        {
          "id": "drill-la-sarga-menos-teatral",
          "title": "Drill, la sarga menos teatral",
          "level": 2
        },
        {
          "id": "chambray-el-azul-que-respira",
          "title": "Chambray, el azul que respira",
          "level": 2
        },
        {
          "id": "canvas-superficie-firme-caida-corta",
          "title": "Canvas, superficie firme, caída corta",
          "level": 2
        },
        {
          "id": "duck-canvas-el-canvas-apretado",
          "title": "Duck canvas, el canvas apretado",
          "level": 2
        },
        {
          "id": "primos-que-conviene-no-mezclar-sin-pensar",
          "title": "Primos que conviene no mezclar sin pensar",
          "level": 2
        },
        {
          "id": "por-que-envejecen-distinto",
          "title": "Por qué envejecen distinto",
          "level": 2
        },
        {
          "id": "una-manera-mas-util-de-mirar-la-ropa",
          "title": "Una manera más útil de mirar la ropa",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/algodon-sarga-denim-canvas-duck-chambray.mdx"
    },
    "dirty-dozen-relojes-militares-y-menswear": {
      "slug": "dirty-dozen-relojes-militares-y-menswear",
      "popularityId": "dirty-dozen-relojes-militares-y-menswear",
      "title": "Dirty Dozen, el canon accidental del reloj militar",
      "excerpt": "Los llamados Dirty Dozen interesan menos por la caza de referencias que por la claridad de su diseño: una lección sobre legibilidad, proporción y utilidad que todavía moldea cómo entendemos un buen reloj de campo.",
      "publishedAt": "2026-01-15",
      "publishedLabel": "15 ene 2026",
      "readTime": "9 min",
      "category": "military-heritage",
      "categoryLabel": "Military Heritage",
      "storyType": "Historia",
      "tags": [
        "Dirty Dozen",
        "Relojes Militares",
        "Military Heritage"
      ],
      "heroImage": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Reloj de pulsera de esfera oscura sobre una superficie de cuero envejecido.",
      "relatedSlugs": [
        "m65-legado-civil",
        "chambray-y-fatiga",
        "ivy-ocbd-y-loafers"
      ],
      "resolvedRelatedSlugs": [
        "m65-legado-civil",
        "chambray-y-fatiga",
        "ivy-ocbd-y-loafers"
      ],
      "featured": false,
      "sections": [
        {
          "id": "que-pedia-realmente-la-especificacion-www",
          "title": "Qué pedía realmente la especificación W.W.W.",
          "level": 2
        },
        {
          "id": "por-que-participaron-doce-fabricantes",
          "title": "Por qué participaron doce fabricantes",
          "level": 2
        },
        {
          "id": "utilidad-militar-proporcion-y-calma-visual",
          "title": "Utilidad militar, proporción y calma visual",
          "level": 2
        },
        {
          "id": "por-que-importan-mas-alla-de-la-lore-del-coleccionista",
          "title": "Por qué importan más allá de la lore del coleccionista",
          "level": 2
        },
        {
          "id": "del-campo-al-armario-civil",
          "title": "Del campo al armario civil",
          "level": 2
        },
        {
          "id": "la-leccion-que-todavia-deja",
          "title": "La lección que todavía deja",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/dirty-dozen-relojes-militares-y-menswear.mdx"
    },
    "sudaderas-crewneck-triangulo-cuello": {
      "slug": "sudaderas-crewneck-triangulo-cuello",
      "popularityId": "sudaderas-crewneck-triangulo-cuello",
      "title": "El pequeño triángulo que explica la sudadera clásica",
      "excerpt": "El inserto en V del cuello no es un misterio esotérico: nació dentro del sportswear de algodón como una solución probable de construcción y absorción, y con el tiempo pasó a ser también una firma visual.",
      "publishedAt": "2026-01-12",
      "publishedLabel": "12 ene 2026",
      "readTime": "9 min",
      "category": "elevated-casual",
      "categoryLabel": "Elevated Casual",
      "storyType": "Historia",
      "tags": [
        "Sweatshirts",
        "Sportswear",
        "Crewneck"
      ],
      "heroImage": "https://images.unsplash.com/photo-1529349462515-1def6992a0d6?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Sudadera gris de cuello redondo sobre una capa base blanca.",
      "relatedSlugs": [
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers",
        "chambray-y-fatiga"
      ],
      "resolvedRelatedSlugs": [
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers",
        "chambray-y-fatiga"
      ],
      "featured": false,
      "sections": [
        {
          "id": "que-era-exactamente-esa-pieza",
          "title": "Qué era exactamente esa pieza",
          "level": 2
        },
        {
          "id": "por-que-algunas-van-solo-delante",
          "title": "Por qué algunas van solo delante",
          "level": 2
        },
        {
          "id": "por-que-existen-las-de-triangulo-delante-y-detras",
          "title": "Por qué existen las de triángulo delante y detrás",
          "level": 2
        },
        {
          "id": "cuando-la-funcion-se-volvio-estilo",
          "title": "Cuando la función se volvió estilo",
          "level": 2
        },
        {
          "id": "como-leerlo-bien-hoy",
          "title": "Cómo leerlo bien hoy",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/sudaderas-crewneck-triangulo-cuello.mdx"
    },
    "champion-reverse-weave-hoodies": {
      "slug": "champion-reverse-weave-hoodies",
      "popularityId": "champion-reverse-weave-hoodies",
      "title": "La hoodie que aprendió a encoger hacia los lados",
      "excerpt": "Reverse Weave no se volvió importante por una etiqueta célebre, sino porque resolvió un problema concreto del fleece de algodón: el encogimiento vertical. Champion convirtió esa corrección en una nueva manera de construir la hoodie seria.",
      "publishedAt": "2026-01-09",
      "publishedLabel": "9 ene 2026",
      "readTime": "9 min",
      "category": "elevated-casual",
      "categoryLabel": "Elevated Casual",
      "storyType": "Iconos",
      "tags": [
        "Champion",
        "Reverse Weave",
        "Hoodies",
        "Sportswear"
      ],
      "heroImage": "https://images.unsplash.com/photo-1594181442022-3e1081d6c2b3?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Sudadera con capucha gris de algodón pesado en un look casual sobrio.",
      "relatedSlugs": [
        "sudaderas-crewneck-triangulo-cuello",
        "camisetas-loopwheeled-merz-whitesville",
        "aaron-levine-elegancia-casual"
      ],
      "resolvedRelatedSlugs": [
        "sudaderas-crewneck-triangulo-cuello",
        "camisetas-loopwheeled-merz-whitesville",
        "aaron-levine-elegancia-casual"
      ],
      "featured": false,
      "sections": [
        {
          "id": "que-significa-realmente-reverse-weave",
          "title": "Qué significa realmente Reverse Weave",
          "level": 2
        },
        {
          "id": "por-que-la-capucha-se-beneficia-especialmente",
          "title": "Por qué la capucha se beneficia especialmente",
          "level": 2
        },
        {
          "id": "los-paneles-laterales-explican-mas-de-la-cuenta",
          "title": "Los paneles laterales explican más de la cuenta",
          "level": 2
        },
        {
          "id": "de-la-pista-al-campus-y-del-campus-a-la-calle",
          "title": "De la pista al campus y del campus a la calle",
          "level": 2
        },
        {
          "id": "por-que-siguen-gustando-tanto",
          "title": "Por qué siguen gustando tanto",
          "level": 2
        },
        {
          "id": "no-es-un-mito-pero-tampoco-un-sacramento",
          "title": "No es un mito, pero tampoco un sacramento",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/champion-reverse-weave-hoodies.mdx"
    },
    "cone-mills-white-oak-gustin-deadstock": {
      "slug": "cone-mills-white-oak-gustin-deadstock",
      "popularityId": "cone-mills-white-oak-gustin-deadstock",
      "title": "El último lote de White Oak todavía corta pantalones",
      "excerpt": "White Oak fue uno de los grandes nombres del denim estadounidense; su cierre convirtió los últimos rollos en stock finito, y marcas como Gustin encontraron ahí una manera muy concreta de vender historia textil sin fingir que el suministro era infinito.",
      "publishedAt": "2026-01-06",
      "publishedLabel": "6 ene 2026",
      "readTime": "8 min",
      "category": "vintage-americana",
      "categoryLabel": "Vintage Americana",
      "storyType": "Historia",
      "tags": [
        "Cone Mills",
        "White Oak",
        "Deadstock",
        "Denim",
        "Gustin"
      ],
      "heroImage": "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Prendas de trabajo y denim colgadas en una barra metálica.",
      "relatedSlugs": [
        "denim-japones-y-mito-americano",
        "chambray-y-fatiga",
        "chore-coat-workwear-fundacional"
      ],
      "resolvedRelatedSlugs": [
        "denim-japones-y-mito-americano",
        "chambray-y-fatiga",
        "chore-coat-workwear-fundacional"
      ],
      "featured": false,
      "sections": [],
      "sourcePath": "content/articles/cone-mills-white-oak-gustin-deadstock.mdx"
    },
    "buzz-rickson-atencion-al-detalle": {
      "slug": "buzz-rickson-atencion-al-detalle",
      "popularityId": "buzz-rickson-atencion-al-detalle",
      "title": "Buzz Rickson's demuestra que el detalle también puede tener alma",
      "excerpt": "Detrás de las flight jackets de Buzz Rickson's hay algo más que fetichismo por la especificación: una manera de entender cómo patrón, tejido, herrajes y etiquetas construyen credibilidad visual.",
      "publishedAt": "2026-01-03",
      "publishedLabel": "3 ene 2026",
      "readTime": "8 min",
      "category": "military-heritage",
      "categoryLabel": "Military Heritage",
      "storyType": "Opinión",
      "tags": [
        "Buzz Rickson's",
        "Reproduction Culture",
        "Flight Jackets"
      ],
      "heroImage": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Chaqueta de cuero de aire militar colgada en un interior sobrio.",
      "relatedSlugs": [
        "m65-legado-civil",
        "denim-japones-y-mito-americano",
        "dirty-dozen-relojes-militares-y-menswear"
      ],
      "resolvedRelatedSlugs": [
        "m65-legado-civil",
        "denim-japones-y-mito-americano",
        "dirty-dozen-relojes-militares-y-menswear"
      ],
      "featured": false,
      "sections": [
        {
          "id": "la-reproduccion-como-metodo-no-como-nostalgia",
          "title": "La reproducción como método, no como nostalgia",
          "level": 2
        },
        {
          "id": "el-patron-es-donde-empieza-la-verdad",
          "title": "El patrón es donde empieza la verdad",
          "level": 2
        },
        {
          "id": "materiales-herrajes-y-etiquetas-la-credibilidad-esta-en-las-piezas-pequenas",
          "title": "Materiales, herrajes y etiquetas: la credibilidad está en las piezas pequeñas",
          "level": 2
        },
        {
          "id": "los-punos-de-punto-explican-mejor-la-marca-que-cualquier-slogan",
          "title": "Los puños de punto explican mejor la marca que cualquier slogan",
          "level": 2
        },
        {
          "id": "la-especificidad-militar-evita-el-pastiche",
          "title": "La especificidad militar evita el pastiche",
          "level": 2
        },
        {
          "id": "cuando-la-obsesion-se-vuelve-convincente",
          "title": "Cuando la obsesión se vuelve convincente",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/buzz-rickson-atencion-al-detalle.mdx"
    },
    "camisetas-loopwheeled-merz-whitesville": {
      "slug": "camisetas-loopwheeled-merz-whitesville",
      "popularityId": "camisetas-loopwheeled-merz-whitesville",
      "title": "Por qué una camiseta loopwheeled cae de otra manera",
      "excerpt": "Las camisetas loopwheeled se han convertido en objeto de deseo por algo más concreto que la nostalgia: un tejido tubular, lento y estable que cambia tacto, caída y comodidad desde la propia construcción.",
      "publishedAt": "2025-12-31",
      "publishedLabel": "31 dic 2025",
      "readTime": "8 min",
      "category": "elevated-casual",
      "categoryLabel": "Elevated Casual",
      "storyType": "Historia",
      "tags": [
        "Loopwheel",
        "Camisetas",
        "Merz b. Schwanen",
        "Whitesville",
        "Elevated Casual"
      ],
      "heroImage": "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Camiseta blanca de algodón con caída suave en un look casual sobrio.",
      "relatedSlugs": [
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers",
        "algodon-sarga-denim-canvas-duck-chambray"
      ],
      "resolvedRelatedSlugs": [
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers",
        "algodon-sarga-denim-canvas-duck-chambray"
      ],
      "featured": false,
      "sections": [
        {
          "id": "que-cambia-en-terminos-de-produccion",
          "title": "Qué cambia en términos de producción",
          "level": 2
        },
        {
          "id": "que-aporta-de-verdad-el-tejido-tubular",
          "title": "Qué aporta de verdad el tejido tubular",
          "level": 2
        },
        {
          "id": "el-beneficio-real-y-la-parte-romantica",
          "title": "El beneficio real y la parte romántica",
          "level": 2
        },
        {
          "id": "por-que-se-sienten-distintas-sobre-el-cuerpo",
          "title": "Por qué se sienten distintas sobre el cuerpo",
          "level": 2
        },
        {
          "id": "merz-b-schwanen-y-whitesville-como-ejemplos-utiles",
          "title": "Merz b. Schwanen y Whitesville como ejemplos útiles",
          "level": 2
        },
        {
          "id": "el-atractivo-cultural-bien-entendido",
          "title": "El atractivo cultural bien entendido",
          "level": 2
        },
        {
          "id": "merecen-la-pena-cuando-se-juzgan-como-camisetas",
          "title": "Merecen la pena cuando se juzgan como camisetas",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/camisetas-loopwheeled-merz-whitesville.mdx"
    },
    "donegal-tweed-neps-y-cultura-textil": {
      "slug": "donegal-tweed-neps-y-cultura-textil",
      "popularityId": "donegal-tweed-neps-y-cultura-textil",
      "title": "Donegal tweed no es una postal rural",
      "excerpt": "El Donegal tweed importa menos como fantasía de campo que como una tela capaz de mezclar aspereza visual, color roto y una elegancia casual muy difícil de sustituir.",
      "publishedAt": "2025-12-28",
      "publishedLabel": "28 dic 2025",
      "readTime": "8 min",
      "category": "elevated-casual",
      "categoryLabel": "Elevated Casual",
      "storyType": "Lo Básico",
      "tags": [
        "Donegal Tweed",
        "Textiles",
        "Tailoring",
        "Elevated Casual"
      ],
      "heroImage": "https://images.unsplash.com/photo-1514222709107-a180c68d72b4?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Tejido de lana gris con textura moteada y caída suave sobre una chaqueta.",
      "relatedSlugs": [
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers",
        "algodon-sarga-denim-canvas-duck-chambray"
      ],
      "resolvedRelatedSlugs": [
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers",
        "algodon-sarga-denim-canvas-duck-chambray"
      ],
      "featured": false,
      "sections": [
        {
          "id": "donde-termina-la-tecnica-y-empieza-el-mito",
          "title": "Donde termina la técnica y empieza el mito",
          "level": 2
        },
        {
          "id": "una-tela-que-trabaja-bien-con-la-luz-y-el-desgaste",
          "title": "Una tela que trabaja bien con la luz y el desgaste",
          "level": 2
        },
        {
          "id": "el-puente-entre-tailoring-y-casual",
          "title": "El puente entre tailoring y casual",
          "level": 2
        },
        {
          "id": "por-que-sigue-importando",
          "title": "Por qué sigue importando",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/donegal-tweed-neps-y-cultura-textil.mdx"
    },
    "trucker-jackets-type-1-2-3": {
      "slug": "trucker-jackets-type-1-2-3",
      "popularityId": "trucker-jackets-type-1-2-3",
      "title": "Type I, II y III: tres chaquetas vaqueras, tres siluetas distintas",
      "excerpt": "Type I, Type II y Type III no son tres nombres intercambiables para la misma chaqueta. Son tres etapas de una evolución concreta, y cada una reorganiza bolsillo, pliegues, ajuste y silueta de una manera distinta.",
      "publishedAt": "2025-12-25",
      "publishedLabel": "25 dic 2025",
      "readTime": "9 min",
      "category": "vintage-americana",
      "categoryLabel": "Vintage Americana",
      "storyType": "Variantes",
      "tags": [
        "Vintage Americana",
        "Denim Jacket",
        "Levi's"
      ],
      "heroImage": "https://images.unsplash.com/photo-1632539965485-d90e8cbca5d3?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Hombre con chaqueta vaquera corta sobre una camiseta blanca, útil para pensar la silueta breve del denim jacket clásico.",
      "relatedSlugs": [
        "denim-japones-y-mito-americano",
        "cone-mills-white-oak-gustin-deadstock",
        "chore-coat-workwear-fundacional"
      ],
      "resolvedRelatedSlugs": [
        "denim-japones-y-mito-americano",
        "cone-mills-white-oak-gustin-deadstock",
        "chore-coat-workwear-fundacional"
      ],
      "featured": false,
      "sections": [
        {
          "id": "type-i-la-chaqueta-de-trabajo-todavia-marcada-por-el-ajuste",
          "title": "Type I, la chaqueta de trabajo todavía marcada por el ajuste",
          "level": 2
        },
        {
          "id": "type-ii-la-transicion-hacia-una-chaqueta-mas-equilibrada",
          "title": "Type II, la transición hacia una chaqueta más equilibrada",
          "level": 2
        },
        {
          "id": "type-iii-la-linea-que-si-fija-la-trucker-moderna",
          "title": "Type III, la línea que sí fija la Trucker moderna",
          "level": 2
        },
        {
          "id": "por-que-cada-una-lee-distinto-aunque-todas-sean-de-denim",
          "title": "Por qué cada una lee distinto aunque todas sean de denim",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/trucker-jackets-type-1-2-3.mdx"
    },
    "german-army-trainers": {
      "slug": "german-army-trainers",
      "popularityId": "german-army-trainers",
      "title": "Las German Army Trainers viven del contraste",
      "excerpt": "Las German Army Trainers siguen importando no por el hype, sino porque resuelven con una claridad rara la relación entre cuero liso, ante gris, suela de goma y proporciones bajas.",
      "publishedAt": "2025-12-22",
      "publishedLabel": "22 dic 2025",
      "readTime": "8 min",
      "category": "military-heritage",
      "categoryLabel": "Military Heritage",
      "storyType": "Iconos",
      "tags": [
        "German Army Trainers",
        "Bundeswehr",
        "Military Heritage",
        "Sneakers"
      ],
      "heroImage": "https://images.unsplash.com/photo-1660614466041-0f42cb0ceb44?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Zapatilla blanca de perfil bajo sobre una superficie de madera.",
      "relatedSlugs": [
        "m65-legado-civil",
        "buzz-rickson-atencion-al-detalle",
        "dirty-dozen-relojes-militares-y-menswear"
      ],
      "resolvedRelatedSlugs": [
        "m65-legado-civil",
        "buzz-rickson-atencion-al-detalle",
        "dirty-dozen-relojes-militares-y-menswear"
      ],
      "featured": false,
      "sections": [
        {
          "id": "un-origen-militar-sin-dramatismo",
          "title": "Un origen militar sin dramatismo",
          "level": 2
        },
        {
          "id": "por-que-funciono-tan-bien-fuera-del-cuartel",
          "title": "Por qué funcionó tan bien fuera del cuartel",
          "level": 2
        },
        {
          "id": "los-detalles-que-de-verdad-importan",
          "title": "Los detalles que de verdad importan",
          "level": 2
        },
        {
          "id": "la-larga-vida-cultural-del-modelo",
          "title": "La larga vida cultural del modelo",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/german-army-trainers.mdx"
    },
    "tartanes-de-casas-barbour-baracuta-y-otras": {
      "slug": "tartanes-de-casas-barbour-baracuta-y-otras",
      "popularityId": "tartanes-de-casas-barbour-baracuta-y-otras",
      "title": "Los cuadros de casa no dicen todos lo mismo",
      "excerpt": "Los cuadros interiores de ciertas chaquetas no son simple decoración: funcionan como sistemas de identidad, memoria textil y señal social. Pero no todos significan lo mismo.",
      "publishedAt": "2025-12-19",
      "publishedLabel": "19 dic 2025",
      "readTime": "9 min",
      "category": "elevated-casual",
      "categoryLabel": "Elevated Casual",
      "storyType": "Variantes",
      "tags": [
        "Tartan",
        "Barbour",
        "Baracuta",
        "Burberry",
        "Textiles"
      ],
      "heroImage": "https://images.unsplash.com/photo-1763909131423-7a5e3301859f?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Chaquetas y abrigos colgados en un interior de tienda, con texturas y cuadros visibles.",
      "relatedSlugs": [
        "donegal-tweed-neps-y-cultura-textil",
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers"
      ],
      "resolvedRelatedSlugs": [
        "donegal-tweed-neps-y-cultura-textil",
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers"
      ],
      "featured": false,
      "sections": [
        {
          "id": "por-que-importa-tanto-un-forro",
          "title": "Por qué importa tanto un forro",
          "level": 2
        },
        {
          "id": "barbour-y-el-tartan-como-garantia-domestica",
          "title": "Barbour y el tartán como garantía doméstica",
          "level": 2
        },
        {
          "id": "baracuta-y-el-tartan-adoptado-como-alma-del-harrington",
          "title": "Baracuta y el tartán adoptado como alma del harrington",
          "level": 2
        },
        {
          "id": "burberry-y-el-check-como-emblema-comercial-total",
          "title": "Burberry y el check como emblema comercial total",
          "level": 2
        },
        {
          "id": "no-todos-los-cuadros-de-casa-significan-lo-mismo",
          "title": "No todos los cuadros de casa significan lo mismo",
          "level": 2
        },
        {
          "id": "lo-que-estos-forros-ensenan-sobre-menswear",
          "title": "Lo que estos forros enseñan sobre menswear",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/tartanes-de-casas-barbour-baracuta-y-otras.mdx"
    },
    "mcgregor-drizzler-eisenhower": {
      "slug": "mcgregor-drizzler-eisenhower",
      "popularityId": "mcgregor-drizzler-eisenhower",
      "title": "La Drizzler no es una Eisenhower",
      "excerpt": "La McGregor Drizzler fijó una idea muy concreta de chaqueta corta civil: cuello simple, cremallera frontal y cintura contenida. Precisamente por eso se confunde tan a menudo con la Eisenhower y otras siluetas vecinas.",
      "publishedAt": "2025-12-16",
      "publishedLabel": "16 dic 2025",
      "readTime": "8 min",
      "category": "ivy",
      "categoryLabel": "Ivy",
      "storyType": "Iconos",
      "tags": [
        "Ivy",
        "McGregor",
        "Drizzler",
        "Eisenhower Jacket"
      ],
      "heroImage": "https://images.unsplash.com/photo-1548897573-896002229eab?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Hombre con chaqueta beige corta de cremallera, útil para leer la proporción limpia de una chaqueta deportiva de medio siglo.",
      "relatedSlugs": [
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers",
        "m65-legado-civil"
      ],
      "resolvedRelatedSlugs": [
        "aaron-levine-elegancia-casual",
        "ivy-ocbd-y-loafers",
        "m65-legado-civil"
      ],
      "featured": false,
      "sections": [
        {
          "id": "que-la-define-de-verdad",
          "title": "Qué la define de verdad",
          "level": 2
        },
        {
          "id": "por-que-se-confunde-tanto-con-otras-chaquetas-cortas",
          "title": "Por qué se confunde tanto con otras chaquetas cortas",
          "level": 2
        },
        {
          "id": "drizzler-frente-a-eisenhower",
          "title": "Drizzler frente a Eisenhower",
          "level": 2
        },
        {
          "id": "la-harrington-entra-en-la-conversacion-pero-no-manda",
          "title": "La Harrington entra en la conversación, pero no manda",
          "level": 2
        },
        {
          "id": "quien-la-llevo-y-como-quedo-fijada-en-la-memoria",
          "title": "Quién la llevó y cómo quedó fijada en la memoria",
          "level": 2
        },
        {
          "id": "lo-que-sigue-ensenando-hoy",
          "title": "Lo que sigue enseñando hoy",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/mcgregor-drizzler-eisenhower.mdx"
    },
    "n1-deck-jacket-y-version-rll": {
      "slug": "n1-deck-jacket-y-version-rll",
      "popularityId": "n1-deck-jacket-y-version-rll",
      "title": "La N-1 nació para una cubierta mojada",
      "excerpt": "La N-1 deck jacket sigue siendo persuasiva porque su atractivo no nace del mito, sino de una ecuación muy concreta entre algodón denso, forro térmico de alpaca y lana, protección contra el viento y una silueta corta que todavía funciona fuera del muelle.",
      "publishedAt": "2025-12-13",
      "publishedLabel": "13 dic 2025",
      "readTime": "8 min",
      "category": "military-heritage",
      "categoryLabel": "Military Heritage",
      "storyType": "Iconos",
      "tags": [
        "N-1 Deck Jacket",
        "US Navy",
        "RRL",
        "Jungle Cloth",
        "Alpaca Wool"
      ],
      "heroImage": "https://images.unsplash.com/photo-1535730142260-496e3db19f6f?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Chaqueta corta de inspiración naval en tono oscuro, pensada como imagen de una prenda de cubierta robusta.",
      "relatedSlugs": [
        "buzz-rickson-atencion-al-detalle",
        "m65-legado-civil",
        "chambray-y-fatiga"
      ],
      "resolvedRelatedSlugs": [
        "buzz-rickson-atencion-al-detalle",
        "m65-legado-civil",
        "chambray-y-fatiga"
      ],
      "featured": false,
      "sections": [
        {
          "id": "que-la-define-visualmente",
          "title": "Qué la define visualmente",
          "level": 2
        },
        {
          "id": "la-logica-del-forro-de-alpaca-y-lana",
          "title": "La lógica del forro de alpaca y lana",
          "level": 2
        },
        {
          "id": "por-que-sigue-siendo-convincente-en-ropa-civil",
          "title": "Por qué sigue siendo convincente en ropa civil",
          "level": 2
        },
        {
          "id": "lo-que-hace-rrl-con-ella",
          "title": "Lo que hace RRL con ella",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/n1-deck-jacket-y-version-rll.mdx"
    },
    "rl67-jacket-importancia-menswear": {
      "slug": "rl67-jacket-importancia-menswear",
      "popularityId": "rl67-jacket-importancia-menswear",
      "title": "La RL67 es Ralph Lauren reducido a chaqueta",
      "excerpt": "La RL67 importa menos como objeto de culto que como una traducción muy precisa de tweed, bolsillos utilitarios y fantasía ecuestre o safari al lenguaje del sport coat contemporáneo.",
      "publishedAt": "2025-12-10",
      "publishedLabel": "10 dic 2025",
      "readTime": "8 min",
      "category": "elevated-casual",
      "categoryLabel": "Elevated Casual",
      "storyType": "Iconos",
      "tags": [
        "Ralph Lauren",
        "RL67",
        "Sport Coat",
        "Elevated Casual",
        "Safari"
      ],
      "heroImage": "https://images.unsplash.com/photo-1765871904025-63a4328aef91?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Hombre con chaqueta de tweed caminando en la ciudad, útil para pensar una silueta de sport coat con aire utilitario.",
      "relatedSlugs": [
        "donegal-tweed-neps-y-cultura-textil",
        "aaron-levine-elegancia-casual",
        "tartanes-de-casas-barbour-baracuta-y-otras"
      ],
      "resolvedRelatedSlugs": [
        "donegal-tweed-neps-y-cultura-textil",
        "aaron-levine-elegancia-casual",
        "tartanes-de-casas-barbour-baracuta-y-otras"
      ],
      "featured": false,
      "sections": [
        {
          "id": "que-es-la-rl67-en-terminos-de-diseno",
          "title": "Qué es la RL67 en términos de diseño",
          "level": 2
        },
        {
          "id": "por-que-importa-dentro-del-universo-ralph-lauren",
          "title": "Por qué importa dentro del universo Ralph Lauren",
          "level": 2
        },
        {
          "id": "bolsillos-cloth-y-la-traduccion-de-lo-utilitario",
          "title": "Bolsillos, cloth y la traducción de lo utilitario",
          "level": 2
        },
        {
          "id": "lo-que-ensena-al-menswear-actual",
          "title": "Lo que enseña al menswear actual",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/rl67-jacket-importancia-menswear.mdx"
    },
    "g1-leather-jacket": {
      "slug": "g1-leather-jacket",
      "popularityId": "g1-leather-jacket",
      "title": "La autoridad tranquila del G-1",
      "excerpt": "El G-1 importa menos como fantasia marcial que como una leccion de proporciones: cuello de mouton, cuero con grano, bolsillos sobrios y una silueta corta que sigue funcionando fuera de la cabina.",
      "publishedAt": "2025-12-07",
      "publishedLabel": "7 dic 2025",
      "readTime": "8 min",
      "category": "military-heritage",
      "categoryLabel": "Military Heritage",
      "storyType": "Iconos",
      "tags": [
        "G-1",
        "Flight Jackets",
        "Naval Aviation"
      ],
      "heroImage": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1600&q=80",
      "heroAlt": "Chaqueta de cuero marron con cuello de borrego, util para pensar la silueta compacta del G-1.",
      "relatedSlugs": [
        "buzz-rickson-atencion-al-detalle",
        "m65-legado-civil",
        "trucker-jackets-type-1-2-3"
      ],
      "resolvedRelatedSlugs": [
        "buzz-rickson-atencion-al-detalle",
        "m65-legado-civil",
        "trucker-jackets-type-1-2-3"
      ],
      "featured": false,
      "sections": [
        {
          "id": "la-silueta-naval-se-lee-en-el-cuello-y-en-el-bajo",
          "title": "La silueta naval se lee en el cuello y en el bajo",
          "level": 2
        },
        {
          "id": "lo-que-lo-define-visualmente",
          "title": "Lo que lo define visualmente",
          "level": 2
        },
        {
          "id": "en-que-se-diferencia-de-las-chaquetas-vecinas",
          "title": "En que se diferencia de las chaquetas vecinas",
          "level": 2
        },
        {
          "id": "por-que-todavia-importa-en-menswear",
          "title": "Por que todavia importa en menswear",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/g1-leather-jacket.mdx"
    },
    "woolrich-arctic-parka-frio-icono-civil": {
      "slug": "woolrich-arctic-parka-frio-icono-civil",
      "popularityId": "woolrich-arctic-parka-frio-icono-civil",
      "title": "La Arctic Parka convirtió el frío serio en icono civil",
      "excerpt": "La Woolrich Arctic Parka importa porque resolvió un problema real de clima extremo y, al hacerlo, fijó una silueta de invierno que todavía hoy parece convincente fuera de la montaña y fuera del uniforme.",
      "publishedAt": "2025-11-26",
      "publishedLabel": "26 nov 2025",
      "readTime": "9 min",
      "category": "vintage-americana",
      "categoryLabel": "Vintage Americana",
      "storyType": "Iconos",
      "tags": [
        "Woolrich",
        "Arctic Parka",
        "Outerwear",
        "Vintage Americana",
        "Winter Clothing"
      ],
      "heroImage": "https://unsplash.com/photos/DOkuHj2FxRM/download?force=true&w=1600",
      "heroAlt": "Parka de invierno con capucha amplia y cuerpo largo usada en un entorno urbano frío.",
      "relatedSlugs": [
        "n1-deck-jacket-y-version-rll",
        "m65-legado-civil",
        "rl67-jacket-importancia-menswear"
      ],
      "resolvedRelatedSlugs": [
        "n1-deck-jacket-y-version-rll",
        "m65-legado-civil",
        "rl67-jacket-importancia-menswear"
      ],
      "featured": false,
      "sections": [
        {
          "id": "el-origen-importa-pero-conviene-contarlo-con-cuidado",
          "title": "El origen importa, pero conviene contarlo con cuidado",
          "level": 2
        },
        {
          "id": "que-resuelve-mejor-que-muchas-parkas-posteriores",
          "title": "Qué resuelve mejor que muchas parkas posteriores",
          "level": 2
        },
        {
          "id": "la-capucha-explica-media-prenda",
          "title": "La capucha explica media prenda",
          "level": 2
        },
        {
          "id": "por-que-visualmente-no-se-parece-a-una-parka-militar",
          "title": "Por qué visualmente no se parece a una parka militar",
          "level": 2
        },
        {
          "id": "el-salto-al-armario-civil-fue-mas-importante-que-cualquier-mito",
          "title": "El salto al armario civil fue más importante que cualquier mito",
          "level": 2
        },
        {
          "id": "lo-que-hay-que-mirar-en-una-buena-arctic-parka",
          "title": "Lo que hay que mirar en una buena Arctic Parka",
          "level": 2
        },
        {
          "id": "por-que-sigue-importando",
          "title": "Por qué sigue importando",
          "level": 2
        }
      ],
      "sourcePath": "content/articles/woolrich-arctic-parka-frio-icono-civil.mdx"
    }
  },
  "articleByPopularityId": {
    "carpenter-chef-painter-fatigue-pierna-recta": "carpenter-chef-painter-fatigue-pierna-recta",
    "sashiko-reparacion-textil-y-menswear": "sashiko-reparacion-textil-y-menswear",
    "chore-coat-workwear-fundacional": "chore-coat-workwear-fundacional",
    "algodon-fibra-larga-origen-calidad": "algodon-fibra-larga-origen-calidad",
    "denim-japones-y-mito-americano": "denim-japones-y-mito-americano",
    "m65-legado-civil": "m65-legado-civil",
    "aaron-levine-elegancia-casual": "aaron-levine-elegancia-casual",
    "ivy-ocbd-y-loafers": "ivy-ocbd-y-loafers",
    "chambray-y-fatiga": "chambray-y-fatiga",
    "wrangler-13mwz-icono-vaquero": "wrangler-13mwz-icono-vaquero",
    "algodon-sarga-denim-canvas-duck-chambray": "algodon-sarga-denim-canvas-duck-chambray",
    "dirty-dozen-relojes-militares-y-menswear": "dirty-dozen-relojes-militares-y-menswear",
    "sudaderas-crewneck-triangulo-cuello": "sudaderas-crewneck-triangulo-cuello",
    "champion-reverse-weave-hoodies": "champion-reverse-weave-hoodies",
    "cone-mills-white-oak-gustin-deadstock": "cone-mills-white-oak-gustin-deadstock",
    "buzz-rickson-atencion-al-detalle": "buzz-rickson-atencion-al-detalle",
    "camisetas-loopwheeled-merz-whitesville": "camisetas-loopwheeled-merz-whitesville",
    "donegal-tweed-neps-y-cultura-textil": "donegal-tweed-neps-y-cultura-textil",
    "trucker-jackets-type-1-2-3": "trucker-jackets-type-1-2-3",
    "german-army-trainers": "german-army-trainers",
    "tartanes-de-casas-barbour-baracuta-y-otras": "tartanes-de-casas-barbour-baracuta-y-otras",
    "mcgregor-drizzler-eisenhower": "mcgregor-drizzler-eisenhower",
    "n1-deck-jacket-y-version-rll": "n1-deck-jacket-y-version-rll",
    "rl67-jacket-importancia-menswear": "rl67-jacket-importancia-menswear",
    "g1-leather-jacket": "g1-leather-jacket",
    "woolrich-arctic-parka-frio-icono-civil": "woolrich-arctic-parka-frio-icono-civil"
  },
  "articlesByCategory": {
    "workwear": [
      "carpenter-chef-painter-fatigue-pierna-recta",
      "sashiko-reparacion-textil-y-menswear",
      "chore-coat-workwear-fundacional",
      "chambray-y-fatiga"
    ],
    "vintage-americana": [
      "denim-japones-y-mito-americano",
      "wrangler-13mwz-icono-vaquero",
      "cone-mills-white-oak-gustin-deadstock",
      "trucker-jackets-type-1-2-3",
      "woolrich-arctic-parka-frio-icono-civil"
    ],
    "military-heritage": [
      "m65-legado-civil",
      "dirty-dozen-relojes-militares-y-menswear",
      "buzz-rickson-atencion-al-detalle",
      "german-army-trainers",
      "n1-deck-jacket-y-version-rll",
      "g1-leather-jacket"
    ],
    "elevated-casual": [
      "aaron-levine-elegancia-casual",
      "sudaderas-crewneck-triangulo-cuello",
      "champion-reverse-weave-hoodies",
      "camisetas-loopwheeled-merz-whitesville",
      "donegal-tweed-neps-y-cultura-textil",
      "tartanes-de-casas-barbour-baracuta-y-otras",
      "rl67-jacket-importancia-menswear"
    ],
    "ivy": [
      "ivy-ocbd-y-loafers",
      "mcgregor-drizzler-eisenhower"
    ]
  },
  "articlesByStoryType": {
    "Lo Básico": [
      "algodon-fibra-larga-origen-calidad",
      "ivy-ocbd-y-loafers",
      "donegal-tweed-neps-y-cultura-textil"
    ],
    "Historia": [
      "sashiko-reparacion-textil-y-menswear",
      "denim-japones-y-mito-americano",
      "dirty-dozen-relojes-militares-y-menswear",
      "sudaderas-crewneck-triangulo-cuello",
      "cone-mills-white-oak-gustin-deadstock",
      "camisetas-loopwheeled-merz-whitesville"
    ],
    "Variantes": [
      "carpenter-chef-painter-fatigue-pierna-recta",
      "algodon-sarga-denim-canvas-duck-chambray",
      "trucker-jackets-type-1-2-3",
      "tartanes-de-casas-barbour-baracuta-y-otras"
    ],
    "Iconos": [
      "chore-coat-workwear-fundacional",
      "m65-legado-civil",
      "wrangler-13mwz-icono-vaquero",
      "champion-reverse-weave-hoodies",
      "german-army-trainers",
      "mcgregor-drizzler-eisenhower",
      "n1-deck-jacket-y-version-rll",
      "rl67-jacket-importancia-menswear",
      "g1-leather-jacket",
      "woolrich-arctic-parka-frio-icono-civil"
    ],
    "Cómo llevarlo": [
      "chambray-y-fatiga"
    ],
    "Opinión": [
      "aaron-levine-elegancia-casual",
      "buzz-rickson-atencion-al-detalle"
    ]
  }
} as const;
